// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBauo5a-CyzUkii2YvSF_JvHyVkKI4eCzY',
    appId: '1:507519544150:web:2f69221c844c0811e984f7',
    messagingSenderId: '507519544150',
    projectId: 'lovecafe-d9766',
    authDomain: 'lovecafe-d9766.firebaseapp.com',
    storageBucket: 'lovecafe-d9766.firebasestorage.app',
    measurementId: 'G-2FH7RHC57L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAprDrr0gzPx8nCr2YvOd6Z5eWtgMGa4_8',
    appId: '1:507519544150:android:7a5d5f101f5511fbe984f7',
    messagingSenderId: '507519544150',
    projectId: 'lovecafe-d9766',
    storageBucket: 'lovecafe-d9766.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBARlP8M5lH3xRfmy5vUU0W92a72wgYx8s',
    appId: '1:507519544150:ios:555f368b381eba44e984f7',
    messagingSenderId: '507519544150',
    projectId: 'lovecafe-d9766',
    storageBucket: 'lovecafe-d9766.firebasestorage.app',
    iosBundleId: 'in.org.lovecafe.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBARlP8M5lH3xRfmy5vUU0W92a72wgYx8s',
    appId: '1:507519544150:ios:17473d4b14764a1ee984f7',
    messagingSenderId: '507519544150',
    projectId: 'lovecafe-d9766',
    storageBucket: 'lovecafe-d9766.firebasestorage.app',
    iosBundleId: 'com.example.cinemaEatsCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBauo5a-CyzUkii2YvSF_JvHyVkKI4eCzY',
    appId: '1:507519544150:web:366409eb236ab6a8e984f7',
    messagingSenderId: '507519544150',
    projectId: 'lovecafe-d9766',
    authDomain: 'lovecafe-d9766.firebaseapp.com',
    storageBucket: 'lovecafe-d9766.firebasestorage.app',
    measurementId: 'G-85X1BQC0VZ',
  );
}
